#include "codegen.h"

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>

void codegen_new(codegen_t* out, ast_chunk_t* chunk)
{
    *out = (codegen_t){
        .blocks = NULL,
        .cap = 0,
        .len = 0,
        .chunk = chunk
    };
}

size_t codegen_generate(codegen_t* generator, ast_chunk_t *chunk)
{
    if (!chunk)
    {
        chunk = generator->chunk;
    }

    size_t index = codegen_allocate_section(generator, chunk);
    size_t nodes_count = chunk->nodes_count;

    for (size_t i = 0; i < nodes_count; i++)
    {
        codegen_process(generator, &chunk->nodes[i], index);
    }

    return index;
}

size_t codegen_allocate_section(codegen_t* generator, ast_chunk_t* chunk)
{
    if (generator->len == generator->cap)
    {
        generator->cap += 16;
        code_block_t* blocks;

        if (generator->len == 0)
        {
            blocks = calloc(generator->cap, sizeof(code_block_t));
        }
        else
        {
            blocks = realloc(generator->blocks, generator->cap * sizeof(code_block_t));
        }

        assert(blocks);
        generator->blocks = blocks;
    }

    size_t index = generator->len++;
    const char* pattern = "__brainfuck%lu";
    size_t count = snprintf(NULL, 0, pattern, index) + 1;
    char* name = malloc(count);
    assert(name);
    snprintf(name, count, pattern, index);

    generator->blocks[index] = (code_block_t){
        .name = name,
        .instructions = NULL,
        .cap = 0,
        .len = 0,
        .chunk = chunk,
    };
    return index;
}

void codegen_println(codegen_t* generator, size_t index, char* line)
{
    code_block_t* block = &generator->blocks[index];

    if (block->len == block->cap)
    {
        block->cap += 16;
        char** instructions;

        if (!block->len)
        {
            instructions = calloc(block->cap, sizeof(char*));
        }
        else
        {
            instructions = realloc(block->instructions, block->cap * sizeof(char*));
        }

        assert(instructions);
        block->instructions = instructions;
    }

    block->instructions[block->len++] = line;
}

#define __snprintf(out, pattern, ...) do { \
    size_t _S = snprintf(NULL, 0, pattern, __VA_ARGS__); \
    out = malloc(_S + 1); \
    assert(out); \
    out[_S] = 0; \
    snprintf(out, _S + 1, pattern, __VA_ARGS__); \
} while (0); \

void codegen_process(codegen_t* generator, ast_node_t* node, size_t section)
{
    static char* early_return = "if (ret) return ret;";
    const char *pattern = NULL;

    switch (node->kind)
    {
    case NODE_EOF:
        {
        }
        break;
    case NODE_RIGHT:
        pattern = "ret = brainfuck_rt_rig(strip, %lu);";
    case NODE_LEFT:
        if (!pattern)
        {
            pattern = "ret = brainfuck_rt_lef(strip, %lu);";
        }
    case NODE_PLUS:
        if (!pattern)
        {
            pattern = "ret = brainfuck_rt_inc(strip, %lu);";
        }
    case NODE_MINUS:
        if (!pattern)
        {
            pattern = "ret = brainfuck_rt_dec(strip, %lu);";
        }
    case NODE_OUTPUT:
        if (!pattern)
        {
            pattern = "ret = brainfuck_rt_out(strip, %lu);";
        }
    case NODE_INPUT:
        {
            if (!pattern)
            {
                pattern = "ret = brainfuck_rt_inp(strip, %lu);";
            }

            char *line;
            __snprintf(line, pattern, node->operands);
            codegen_println(generator, section, line);
            codegen_println(generator, section, early_return);
        } break;

    case NODE_LOOP:
        {
            size_t i = codegen_generate(generator, node->chunk);
            char *name = generator->blocks[i].name;

            char *line;
            __snprintf(line, "ret = brainfuck_rt_loop(strip, %s);", name);
            codegen_println(generator, section, line);
            codegen_println(generator, section, early_return);
        } break;
    }
}

void codegen_dump(codegen_t generator)
{
    for (size_t i = 0; i < generator.len; i++)
    {
        code_block_t block = generator.blocks[i];

        printf("%s:\n", block.name);

        for (size_t j = 0; j < block.len; j++)
        {
            printf("    /* %03lu */ %s\n", j, block.instructions[j]);
        }
    }
}

int codegen_flush(codegen_t generator, FILE *output)
{
    fprintf(output, "// Generated by the bfc program.\n\n");
    fprintf(output, "#include <librt.h>\n\n");

    // declarations
    for (size_t i = 0; i < generator.len; i++)
    {
        code_block_t block = generator.blocks[i];

        fprintf(output, "static int %s(struct strip_t *);\n", block.name);
    }

    fprintf(output, "\n");

    // implementations
    for (size_t i = 0; i < generator.len; i++)
    {
        code_block_t block = generator.blocks[i];

        fprintf(output, "int %s(struct strip_t *strip)\n{\n", block.name);
        fprintf(output, "    int ret;\n");

        for (size_t j = 0; j < block.len; j++)
        {
            fprintf(output, "    %s\n", block.instructions[j]);
        }

        fprintf(output, "    return 0;\n}\n\n");
    }

    // main generation
    fprintf(output, "int main(void)\n");
    fprintf(output, "{\n");
    fprintf(output, "    int ret;\n");
    fprintf(output, "    struct strip_t strip;\n");
    fprintf(output, "    if ((ret = brainfuck_rt_init(&strip))) return ret;\n");
    fprintf(output, "    if ((ret = __brainfuck0(&strip))) return ret;\n");
    fprintf(output, "    brainfuck_rt_deinit(&strip); // cannot fail\n");
    fprintf(output, "    return 0;\n");
    fprintf(output, "}\n");
    return ferror(output);
}
